# Generated by Django 3.2.5 on 2021-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=112)),
                ('content', models.TextField()),
            ],
        ),
    ]
